version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
