name: CI
on:
  pull_request:
    branches: main
  push:
    branches: main
permissions:
  contents: read
  packages: write
concurrency:
  group: ci-${{github.ref}}
  cancel-in-progress: ${{github.ref != 'refs/heads/main'}}
jobs:
  build:
    name: Build (msvc-${{matrix.msvc}})
    runs-on: windows-latest
    strategy:
      matrix:
        msvc:
          - 15
          - 16
    steps:
      - name: Gather info
        id: info
        run: |
          $package = 'ghcr.io/${{github.repository_owner}}/build-windows'
          $tag = "${package}:msvc-${{matrix.msvc}}".ToLower()
          echo "::set-output name=tag::$tag"
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Build image
        run: >
          docker build .
          -t ${{steps.info.outputs.tag}}
          --build-arg VS_VERSION=${{matrix.msvc}}
      - name: Report image details
        run: >
          docker image history
          --format "table {{.Size}}\t{{.CreatedBy}}"
          ${{steps.info.outputs.tag}}
      - name: Run tests
        run: >
          docker run --rm ${{steps.info.outputs.tag}}
          'cl /help -and link /help -and cmake --version -and
          ninja --version -and msbuild /version -and git --version -and
          python --version -and sccache --version'
      - name: Log into registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{github.token}}
      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: docker push ${{steps.info.outputs.tag}}
